<a href="https://colab.research.google.com/github/maryamalzahrani/assignment_w5_c1/blob/main/assignment_w5_c1_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [1]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.
import pandas
import numpy as np
import pandas as pd
import yfinance as yf

#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [2]:
pip install yfinance

In [3]:
!pip install matplotlib-venn

In [4]:
!apt-get -qq install -y libfluidsynth1

In [31]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = 'APPLE'

In [6]:
import datetime

In [7]:
pip install git-timestamp

In [8]:
dft = pdr.get_data_yahoo(stock_symbol,pandas.Timestamp('2019'), pandas.Timestamp('2021'))

[*********************100%***********************]  1 of 1 completed


In [9]:
np.nan

nan

In [10]:
type(np.nan)

float

In [11]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.

df = pdr.get_data_yahoo(stock_symbol,pandas.Timestamp('2019'), pandas.Timestamp('2021'))
df = df[['Open','High','Low','Close']]
df = df.dropna()

[*********************100%***********************]  1 of 1 completed


In [12]:
df.rolling(window=2)

Rolling [window=2,center=False,axis=0]

In [13]:
df.rolling(window=2).apply(np.sum)

Open        High         Low       Close
Date                                                      
2019-01-02         NaN         NaN         NaN         NaN
2019-01-03   74.717499   76.142502   74.057499   75.027500
2019-01-04   72.127499   73.567501   71.450001   72.612499
2019-01-07   73.307499   74.345001   72.424999   74.047497
2019-01-08   74.564999   75.162502   73.605000   74.669998
...                ...         ...         ...         ...
2020-12-24  263.480011  265.889999  261.880005  262.930008
2020-12-28  265.310013  270.800003  264.610001  268.660004
2020-12-29  272.040009  276.129990  267.849991  271.559998
2020-12-30  273.630005  274.779999  267.739990  268.589996
2020-12-31  269.660004  270.730011  265.119995  266.410004

[505 rows x 4 columns]

In [14]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df['Close'].rolling(window=15).mean()
df['Open_1_Change'] = df['Open'].diff()
df =df.dropna()
X = df

In [15]:
X

Open        High  ...  Close_15_Rolling  Open_1_Change
Date                                ...                                 
2019-01-23   38.537498   38.785000  ...         38.072667      -0.565002
2019-01-24   38.527500   38.619999  ...         37.985667      -0.009998
2019-01-25   38.869999   39.532501  ...         38.245167       0.342499
2019-01-28   38.947498   39.082500  ...         38.379167       0.077499
2019-01-29   39.062500   39.532501  ...         38.491667       0.115002
...                ...         ...  ...               ...            ...
2020-12-24  131.320007  133.460007  ...        126.245333      -0.839996
2020-12-28  133.990005  137.339996  ...        127.208000       2.669998
2020-12-29  138.050003  138.789993  ...        127.949333       4.059998
2020-12-30  135.580002  135.990005  ...        128.572000      -2.470001
2020-12-31  134.080002  134.740005  ...        129.299334      -1.500000

[491 rows x 6 columns]

In [30]:
df

Open        High  ...  Close_15_Rolling  Open_1_Change
Date                                ...                                 
2019-01-23   38.537498   38.785000  ...         38.072667      -0.565002
2019-01-24   38.527500   38.619999  ...         37.985667      -0.009998
2019-01-25   38.869999   39.532501  ...         38.245167       0.342499
2019-01-28   38.947498   39.082500  ...         38.379167       0.077499
2019-01-29   39.062500   39.532501  ...         38.491667       0.115002
...                ...         ...  ...               ...            ...
2020-12-24  131.320007  133.460007  ...        126.245333      -0.839996
2020-12-28  133.990005  137.339996  ...        127.208000       2.669998
2020-12-29  138.050003  138.789993  ...        127.949333       4.059998
2020-12-30  135.580002  135.990005  ...        128.572000      -2.470001
2020-12-31  134.080002  134.740005  ...        129.299334      -1.500000

[491 rows x 6 columns]

In [16]:
X.isna().any()

Open                False
High                False
Low                 False
Close               False
Close_15_Rolling    False
Open_1_Change       False
dtype: bool

In [17]:
df.Close

Date
2019-01-23     38.480000
2019-01-24     38.174999
2019-01-25     39.439999
2019-01-28     39.075001
2019-01-29     38.669998
                 ...    
2020-12-24    131.970001
2020-12-28    136.690002
2020-12-29    134.869995
2020-12-30    133.720001
2020-12-31    132.690002
Name: Close, Length: 491, dtype: float64

In [18]:
df.Close.diff(-1) == (df.Close.shift(-1) - df.Close)

Date
2019-01-23    False
2019-01-24    False
2019-01-25    False
2019-01-28    False
2019-01-29    False
              ...  
2020-12-24    False
2020-12-28    False
2020-12-29    False
2020-12-30    False
2020-12-31    False
Name: Close, Length: 491, dtype: bool

In [19]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.

y = np.where((df.Close.shift(-1)-df['Close'])>=0,1,-1)

In [20]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train = X[:index]
X_test = X[index:]
y_train = y[:index]
y_test =  y[index:]

logistic = LogisticRegression()
logistic = logistic.fit(X_train,y_train)
probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)
print(sklearn.metrics.classification_report(y_pred=predictions,y_true=y_test))



pred_df = df.iloc[index:]

pred_df['true_labe1'] = y_test
pred_df['prediction'] = predictions

# close to close difference 
c2c_price = pred_df.Close.shift(-1) - pred_df.Close #


returns = pred_df.prediction*c2c_price

trend_trading_rule = pred_df['Close_15_Rolling']<pred_df['Open']

pred_df['returns'] = returns
pred_df['c_returns'] = returns.cumsum()

# Trade cost analysis

pred_df['trade_cost'] = 1.00 *2 # tow trades per day, 1$ per trade.
cumlative_cost = pred_df['trade_cost'].cumsum()

pred_df['cum_returns_w_cost'] = returns.cumsum() - cumlative_cost

#pred_df['trend_trading_rule'] = trend_trading_rule
#pred_df['trend_trading_returns'] = trend_trading_rule*c2c_price
#pred_df['trend_trading_c_returns'] = pred_df['trend_trading_returns'].cumsum()




              precision    recall  f1-score   support

          -1       0.48      0.46      0.47        65
           1       0.59      0.60      0.60        83

    accuracy                           0.54       148
   macro avg       0.53      0.53      0.53       148
weighted avg       0.54      0.54      0.54       148



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stab

In [21]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit(X_train, y_train)

In [22]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                       1
0              Open    [0.4152975609973697]
1              High   [-0.1113023732832014]
2               Low   [0.11226979082129279]
3             Close   [-0.3483215718736895]
4  Close_15_Rolling  [-0.06807358361157423]
5     Open_1_Change  [-0.16938733434669015]

In [23]:
pd.DataFrame({'colum':X.columns.values, 'b': logistic.coef_.ravel()})

colum         b
0              Open  0.415298
1              High -0.111302
2               Low  0.112270
3             Close -0.348322
4  Close_15_Rolling -0.068074
5     Open_1_Change -0.169387

In [24]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)

In [25]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

metrics.confusion_matrix(y_test, predictions)

array([[30, 35],
       [33, 50]])

In [32]:
# Alternative method using report classfication 

print(sklearn.metrics.classification_report(y_pred = predictions,y_true= y_test))

              precision    recall  f1-score   support

          -1       0.48      0.46      0.47        65
           1       0.59      0.60      0.60        83

    accuracy                           0.54       148
   macro avg       0.53      0.53      0.53       148
weighted avg       0.54      0.54      0.54       148



In [26]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.

logistic.score(X_test, y_test)

0.5405405405405406

In [27]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(LogisticRegression() ,X_test, y_test)
cross_val

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.56666667, 0.73333333, 0.53333333, 0.51724138, 0.65517241])

In [29]:
cross_val

array([0.56666667, 0.73333333, 0.53333333, 0.51724138, 0.65517241])